/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.remotetokenizer.core;

import com.remotetokenizer.models.User;
import com.remotetokenizer.providers.Tokenizer;
import com.remotetokenizer.providers.XMLStream;
import com.remotetokenizer.contracts.IAlert;
import com.remotetokenizer.contracts.IAuthentication;
import com.remotetokenizer.contracts.IRegister;
import com.remotetokenizer.contracts.IRetriever;
import com.remotetokenizer.contracts.ITokenizer;
import com.remotetokenizer.providers.WriteMode;
import java.awt.event.ItemEvent;
import java.rmi.RemoteException;
import java.rmi.registry.LocateRegistry;
import java.rmi.registry.Registry;
import java.rmi.server.UnicastRemoteObject;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.UUID;
import java.util.concurrent.ConcurrentHashMap;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Georgi Spasov
 */
public class Server extends javax.swing.JFrame {

    private final Map<UUID, User> logedUsers;

    /**
     * Creates new form Server
     */
    public Server() {
        initComponents();

        logedUsers = new ConcurrentHashMap<>();//TODO: Concurent==========================
        btnConnection.addItemListener((ItemEvent ev) -> {
            if (ev.getStateChange() == ItemEvent.SELECTED) {
                btnConnection.setText("Stop");
            } else if (ev.getStateChange() == ItemEvent.DESELECTED) {
                btnConnection.setText("Run");
            }
        });
    }

    // Server methods ==========================================================
    public void startServer(int portNumber) throws RemoteException {
        try {
            Registry registry = LocateRegistry.createRegistry(portNumber);
            IAuthentication authentication = new AuthenticationService();
            registry.rebind(IAuthentication.LOOKUPNAME, authentication);
            ITokenizer tokenizer = new TokenizerService();
            registry.rebind(ITokenizer.LOOKUPNAME, tokenizer);
            IRetriever retriever = new RetrieverService();
            registry.rebind(IRetriever.LOOKUPNAME, retriever);
            IRegister registrar = new RegisterUserService();
            registry.rebind(IRegister.LOOKUPNAME, registrar);
            this.txtServerLog
                    .append((String.format("%s Service running at %d port...\n", IAuthentication.LOOKUPNAME, portNumber)));
            this.txtServerLog
                    .append((String.format("%s Service running at %d port...\n", ITokenizer.LOOKUPNAME, portNumber)));
            this.txtServerLog
                    .append((String.format("%s Service running at %d port...\n", IRetriever.LOOKUPNAME, portNumber)));
            this.txtServerLog
                    .append((String.format("%s Service running at %d port...", IRegister.LOOKUPNAME, portNumber)));
        } catch (RemoteException e) {
            System.out.println(e.getMessage());
            e.printStackTrace();
        }
    }

    // Server methods ==========================================================
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlServerGUI = new javax.swing.JPanel();
        tabsServer = new javax.swing.JTabbedPane();
        pnlHome = new javax.swing.JPanel();
        btnConnection = new javax.swing.JToggleButton();
        lblStatus = new javax.swing.JLabel();
        lblStatusOutput = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtServerLog = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnListTokens = new javax.swing.JButton();
        btnListCards = new javax.swing.JButton();
        btnSaveTokens = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtTokensOutput = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        btnAllUsers = new javax.swing.JButton();
        txtFindUser = new javax.swing.JTextField();
        btnFindUser = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtUsersOutput = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Remote Tokenizer Server");

        btnConnection.setText("Run");
        btnConnection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnectionActionPerformed(evt);
            }
        });

        lblStatus.setText("Status");

        lblStatusOutput.setText("Not running");

        txtServerLog.setEditable(false);
        txtServerLog.setColumns(20);
        txtServerLog.setRows(5);
        jScrollPane1.setViewportView(txtServerLog);

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addComponent(lblStatus)
                        .addGap(18, 18, 18)
                        .addComponent(lblStatusOutput, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                        .addComponent(btnConnection)))
                .addContainerGap())
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConnection)
                    .addComponent(lblStatus)
                    .addComponent(lblStatusOutput))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsServer.addTab("Home", pnlHome);

        btnListTokens.setText("Tokens");

        btnListCards.setText("Card IDs");

        btnSaveTokens.setText("Save to File");

        txtTokensOutput.setEditable(false);
        txtTokensOutput.setColumns(20);
        txtTokensOutput.setRows(5);
        jScrollPane2.setViewportView(txtTokensOutput);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnListTokens)
                        .addGap(18, 18, 18)
                        .addComponent(btnListCards)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaveTokens)
                        .addGap(0, 135, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnListTokens)
                    .addComponent(btnListCards)
                    .addComponent(btnSaveTokens))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsServer.addTab("Tokens", jPanel1);

        btnAllUsers.setText("All Users");

        txtFindUser.setText("Username");

        btnFindUser.setText("Find");

        txtUsersOutput.setEditable(false);
        txtUsersOutput.setColumns(20);
        txtUsersOutput.setRows(5);
        jScrollPane3.setViewportView(txtUsersOutput);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(txtFindUser, javax.swing.GroupLayout.DEFAULT_SIZE, 257, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFindUser)
                        .addGap(18, 18, 18)
                        .addComponent(btnAllUsers)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAllUsers)
                    .addComponent(txtFindUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFindUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabsServer.addTab("Users", jPanel2);

        javax.swing.GroupLayout pnlServerGUILayout = new javax.swing.GroupLayout(pnlServerGUI);
        pnlServerGUI.setLayout(pnlServerGUILayout);
        pnlServerGUILayout.setHorizontalGroup(
            pnlServerGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabsServer, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        pnlServerGUILayout.setVerticalGroup(
            pnlServerGUILayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlServerGUILayout.createSequentialGroup()
                .addComponent(tabsServer, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlServerGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlServerGUI, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnConnectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnectionActionPerformed
        try {
            // TODO add your handling code here:
            startServer(1099);
        } catch (RemoteException ex) {
            Logger.getLogger(Server.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnConnectionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws RemoteException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Server.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        // Server methods ======================================================
        // Server methods ======================================================  
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Server().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAllUsers;
    private javax.swing.JToggleButton btnConnection;
    private javax.swing.JButton btnFindUser;
    private javax.swing.JButton btnListCards;
    private javax.swing.JButton btnListTokens;
    private javax.swing.JButton btnSaveTokens;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblStatusOutput;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JPanel pnlServerGUI;
    private javax.swing.JTabbedPane tabsServer;
    private javax.swing.JTextField txtFindUser;
    private javax.swing.JTextArea txtServerLog;
    private javax.swing.JTextArea txtTokensOutput;
    private javax.swing.JTextArea txtUsersOutput;
    // End of variables declaration//GEN-END:variables

    class AuthenticationService extends UnicastRemoteObject implements IAuthentication {

        public AuthenticationService() throws RemoteException {
        }

        @Override
        public UUID authenticate(String username, String password, IAlert alertUser) throws RemoteException {
            XMLStream stream = new XMLStream();
            User logedUser;
            UUID sentCookie = null;
            List<User> usersFromXML = stream.<ArrayList<User>>readXML("users.xml");
            logedUser = usersFromXML
                    .stream()
                    .filter(u -> (u.getName() == null ? username == null : u.getName().equals(username))
                    && (u.getPassword() == null ? password == null : u.getPassword().equals(password)))
                    .findFirst().orElse(null);
            if (logedUser != null) {
                sentCookie = UUID.randomUUID();
                logedUsers.put(sentCookie, logedUser);
                alertUser.alert("Login Success");
            } else {
                alertUser.alert("Login Failed");
            }
            return sentCookie;
        }

        @Override
        public void logOut(UUID cookie, IAlert alertUser) throws RemoteException {
            logedUsers.remove(cookie);
            alertUser.alert("Logged out");
        }

    }

    class TokenizerService extends UnicastRemoteObject implements ITokenizer {

        public TokenizerService() throws RemoteException {
        }

        @Override
        public String createToken(String cardId, UUID cookie, IAlert alertUser) throws RemoteException {
            String result = "";
            boolean canTokenize = true == logedUsers.get(cookie).getCanTokenize();
            if (canTokenize) {
                Tokenizer tokenizer = new Tokenizer();
                boolean cardIdCheck = tokenizer.checkCardId(cardId); //========================
                if (cardIdCheck) {
                    result = tokenizer.tokenize(cardId);
                    XMLStream stream = new XMLStream();
                    Map<String, String> tokensFromXML = stream.<HashMap<String, String>>readXML("tokens.xml");
                    tokensFromXML.put(result, cardId);
                    stream.<Map<String, String>>writeXML(tokensFromXML, "tokens.xml", WriteMode.UPDATE);
                    alertUser.alert("CardId tokenized.");
                } else {
                    alertUser.alert("Wrong card id number!");
                }
            } else {
                alertUser.alert("Unauthorized to tokenize!");
            }
            return result;
        }
    }

    class RetrieverService extends UnicastRemoteObject implements IRetriever {

        public RetrieverService() throws RemoteException {
        }

        @Override
        public String getCardId(String token, UUID cookie, IAlert alertUser) throws RemoteException {
            String result = "";
            boolean canRetrieve = true == logedUsers.get(cookie).getCanRetrieve();
            if (canRetrieve) {
                XMLStream stream = new XMLStream();
                result = stream.<HashMap<String, String>>readXML("tokens.xml")
                        .get(token);
                if (!result.isEmpty()) {
                    alertUser.alert("Card Id retrieved.");
                } else {
                    alertUser.alert("Card Id not tokenized!");
                }
            } else {
                alertUser.alert("Unauthorized to retrieve!");
            }
            return result;
        }
    }

    class RegisterUserService extends UnicastRemoteObject implements IRegister {

        public RegisterUserService() throws RemoteException {
        }

        @Override
        public void register(String name, String password, boolean canTokenize, boolean canRetrieve, UUID cookie, IAlert alertUser) throws RemoteException {
            XMLStream stream = new XMLStream();
            List<User> usersFromXML = stream.<ArrayList<User>>readXML("users.xml");
            User newUser = new User(name, password, canTokenize, canRetrieve);
            usersFromXML.add(newUser);
            stream.<List<User>>writeXML(usersFromXML, "users.xml", WriteMode.UPDATE);
            alertUser.alert("User registered.");
        }
    }
}
